# $schema: http://json.schemastore.org/github-workflow.json
name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  verify-github-workflows:
    uses: harmelodic/workflows/.github/workflows/verify-github-workflows.yaml@640f0950bdc5329e41fe0a187c2ccfe69e645fd3

  build-browser-extension:
    uses: harmelodic/workflows/.github/workflows/build-browser-extension.yaml@640f0950bdc5329e41fe0a187c2ccfe69e645fd3
    with:
      extension-name: minimal-grey-chrome
      release-version: ${{ github.sha }}
