name: main

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y jq
      - id: manifest-version
        run: echo "version=$(jq -r '.version' src/manifest.json)" >> "$GITHUB_OUTPUT"
      - run: zip -r "minimal-grey-chrome.${{ steps.manifest-version.outputs.version }}.zip" src
      - run: git tag -a "${{ steps.manifest-version.outputs.version }}" -m "${{ steps.manifest-version.outputs.version }}"
      - run: git push --follow-tags
