# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@6c1cca7559114938dce36c7707fe228600bfa253
    with:
      extension-name: minimal-grey-chrome
      release-version: ${{ github.ref_name }}
