# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@640f0950bdc5329e41fe0a187c2ccfe69e645fd3
    with:
      extension-name: minimal-grey-chrome
      release-version: ${{ github.ref_name }}
