# $schema: http://json.schemastore.org/github-workflow.json
name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release-browser-extension:
    uses: harmelodic/workflows/.github/workflows/release-browser-extension.yaml@1d104e508f3b193163308c2abf59c013863b9b5d
    with:
      extension-name: minimal-grey-chrome
      release-version: ${{ github.ref_name }}
