name: tag

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
      - run: git config user.name "GitHub Actions"
      - run: git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: |
          cd src
          zip -r "minimal-grey-chrome.${{ github.ref_name }}.zip" .
      - uses: actions/github-script@v7
        env:
          MANIFEST_VERSION: ${{ github.ref_name }}
        with:
          script: |
            const fs = require('fs').promises;
            
            const filePath = `minimal-grey-chrome.${process.env.MANIFEST_VERSION}.zip`
            
            const release = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: process.env.MANIFEST_VERSION,
              name: process.env.MANIFEST_VERSION
            })
            
            github.rest.repos.uploadReleaseAsset({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: filePath,
              data: await fs.readFile(filePath),
            });
